/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_brilliantservice_bluetooth_BlueScan */

#ifndef _Included_jp_co_brilliantservice_bluetooth_BlueScan
#define _Included_jp_co_brilliantservice_bluetooth_BlueScan
#define TAG "BluetoothNDK"
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_brilliantservice_bluetooth_BlueScan
 * Method:    btDeviceScan
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jp_co_brilliantservice_bluetooth_BlueScan_btDeviceScan
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_brilliantservice_bluetooth_BlueScan
 * Method:    client
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_co_brilliantservice_bluetooth_BlueScan_client
  (JNIEnv *, jobject);

/*
 * Class:     jp_co_brilliantservice_bluetooth_BlueScan
 * Method:    server
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_jp_co_brilliantservice_bluetooth_BlueScan_server
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
